### ISSUE TITLE
No OpenAPI

### ISSUE THREAD

**Issue by blkluv** [hc-psy/blender-gpt#5]
Their is no option to add an API key once installed.

**Comment by ryvn-dev** [comment]
Hi,

For entering your Open-AI API key, please go to `Edit` > `Preferences` > install blender-gpt add-on > Check the box next to `Object: Blender GPT` > The input area will show up. (see below figure)

<img width="563" alt="截圖 2023-06-12 下午8 21 55" src="https://github.com/hc-psy/blender-gpt/assets/37497872/eb52cdc1-9937-484b-990d-91941e5268dd">

If you still got problems, please let me know more about the specifications of your blender, OS, etc.

**Comment by hahzterry** [comment]
Blender 3.4.1 
[https://www.arvrtise.com/wp-content/uploads/2023/06/Screenshot.jpg](url)

**Comment by ARCIST-AI** [comment]
It wont let me paste my key into the box. Im running os x monterey with an edge browser.

**Comment by ARCIST-AI** [comment]
> Hi,
> 
> For entering your Open-AI API key, please go to `Edit` > `Preferences` > install blender-gpt add-on > Check the box next to `Object: Blender GPT` > The input area will show up. (see below figure)
> 
> <img alt="截圖 2023-06-12 下午8 21 55" width="563" src="https://user-images.githubusercontent.com/37497872/245141849-eb52cdc1-9937-484b-990d-91941e5268dd.png">
> If you still got problems, please let me know more about the specifications of your blender, OS, etc.

Im running os x Monterey with the Edge browser. Blender GPT was the latest version a couple of days ago. But i think the real problem is the app im using as a remote keypad called “remote+”. 
Im quadriplegic so this is the way i have to use a computer. The app has lots of settings but i cant find anything in the way of permissions for clipboard.

<img width="1920" alt="blend" src="https://github.com/hc-psy/blender-gpt/assets/96149457/23635e98-e126-428d-9087-a3bfe37c8865">

**Comment by ryvn-dev** [comment]
We've tested on various OS and Blender versions without "remote+" and all works fine. Could you try inputting your API key manually, letter by letter? Let us know if you have more questions.

Thank you!
